### ISSUE TITLE
Add a reputation system

### ISSUE THREAD

**Issue by ghost** [godwhoa/oodle#15]
My idea is to add a reputation system which will let users of a certain channel vote another user which helped them solving a problem he had. 
For example: I ask for helping to solve a problem I have for a while and someone helps me out. The next thing I'll do to show appreciation is to tell oodle to give him another point to his rank. 
.give +1 name of user 
output: oodle: <name of user> Got one point from user _name

If you want to find out how many points you have you'd type: 
.rank my_user_name 
output: oodle: my_user_name has x points. 

Rules: 
* You can't give more than 2 points at once. 
* If you give someone 2 points (showing a lot of appreciation for his/hers help) then you'd have to wait another 8h before you're able to give any points to someone (to prevent spam)
* If you give someone 1 point you'd have to wait another 5h before you can give points to someone.  
* If you try to give someone points but you have to wait it would be nice to make oodle to show some message so the user knows he must wait before he can rank someone again.
* You can't give yourself points :)
* You can also downgrade someone's rank by doing: .give -1 name of user

*Also, the ranking system should be stored in a database or on the local server where oodle is running, maybe in a text file.*
*You can make something like a 'hearth beat' request to server at every X minutes and see if '.seen' for all current users returns less than 10 minutes. If it does then show their rank because they just entered the channel.*

It would be interesting but not mandatory to also specify a reason why you give/take a point from someone.

**Comment by solenum** [comment]
To extend on this,

Make the command be .rep <username> or something similar, no +1 because the user can only ever give a single point thus its redundant text, and no - because negative points is just a source of arguments.

To summarize 

- Let the command be '.rep <username>' or something similar.
- Don't have negative rep/downvoting.
- One point at a time.
- Don't make the cooldown for .rep 8 hours, thats insane.  Keep it to an 30 minutes or an hour, max.
- Have the cooldown be per user your rep, so if you rep one user you cant rep that specific user for X time.

> Also, the ranking system should be stored in a database or on the local server where oodle is running, maybe in a text file.

oodle uses sqlite.

**Comment by godwhoa** [comment]
> Let the command be '.rep ' or something similar.

This is what I settled on
```
# Giving
.rep <point> <other user>

# Querying
.rep <user>
```

**Comment by solenum** [comment]
Could you consider removing the <point> argument, as oodnet won't have downvoting and having the ability to give more than two points is...silly.  Also change the query command to .rank?

if not I'll just have to fork I suppose.

**Comment by ghost** [comment]
I disagree completely with @exezin, @godwhoa, but do as you please.

**Comment by BitPuffin** [comment]
For the cooldown time I don't see why that's not something you can have in the configuration file. Put whatever default and let the host change it to what they want.

**Comment by solenum** [comment]
One important thing I think we've all forgotten about, the rep system should only work on registered/auth'd nicks.

**Comment by godwhoa** [comment]
Changed the commands to:
```
.give <point> <user>
.rank <user>
```
And cooldowns/points are gonna be configurable. Still haven't decided how they'll be defined in config.

**Comment by ghost** [comment]
I took your latest release and tried it for a bit to test the reputation system. It seems like I'm able to give points to anyone even if they are not in the same channel as I am.

**Comment by solenum** [comment]
I'm probably going to need to fork this and learn golang to make my own changes because @godwhoa is reluctant to make this system sane.

**Comment by godwhoa** [comment]
> I took your latest release and tried it for a bit to test the reputation system. It seems like I'm able to give points to anyone even if they are not in the same channel as I am.

Fixed

@Murii  what do you think of restricting it to registered/auth'd nicks.?

**Comment by ghost** [comment]
@godwhoa If you're able to check weather or not a user is registered then I'd take the proposal into consideration. Having said that, it doesn't sound like a bad idea but I think you should let the admin decide by having a special ID inside the configure file.
My personal opinion is that you shouldn't force users to register themselves in order to get ranked because as you know some channels won't allow you to speak if you are not registered so they won't get ranked anyway, basically it's up to admin.

**Comment by godwhoa** [comment]
> If you're able to check weather or not a user is registered then I'd take the proposal into consideration.

It is possible but it depends on each irc network. Tested it on freenode and it could detect.

> I think you should let the admin decide by having a special ID inside the configure file

:+1:

**Comment by godwhoa** [comment]
For any bugs and features open another issue.
