### ISSUE TITLE
Support for Uncylopedia and Wikipedia

### ISSUE THREAD

**Issue by ghost** [godwhoa/oodle#25]
Besides hackterm, I think, it would be a good idea to support these two sites for quick references:
* https://en.uncyclopedia.co/
* https://en.wikipedia.org/wiki/Main_Page
Under the names: .clopedia <page> and .wiki <page>

**Comment by godwhoa** [comment]
Found an API for wikipedia:
https://en.wikipedia.org/w/api.php?format=json&action=query&prop=extracts&exintro=&explaintext=&titles=Google
but couldn't find one for uncyclopedia that would let me get extracts.

**Comment by godwhoa** [comment]
Closed with: https://github.com/godwhoa/oodle/commit/28fb19bf059d1af841082f05d283dbbbe6f52014
